Update workflows

diff --git a/.github/workflows/add-listing-image.yaml b/.github/workflows/add-listing-image.yaml
--- a/.github/workflows/add-listing-image.yaml
+++ b/.github/workflows/add-listing-image.yaml
@@ -69,9 +69,9 @@ jobs:
           item_number="${{ github.event.issue.title }}"
           body='${{ github.event.issue.body }}'
           if [[ "$body" =~ src=\"([^\"]+)\" ]]; then
-              img_url="${BASH_REMATCH[1]}"
+            img_url="${BASH_REMATCH[1]}"
           elif [[ "$body" =~ \[.*\]\((https?://[^\)]+) ]]; then
-              img_url="${BASH_REMATCH[1]}"
+            img_url="${BASH_REMATCH[1]}"
           else
             echo "Error: No image URL found in the issue body."
             echo "Debugging: ${BASH_REMATCH[1]}"
@@ -134,20 +134,20 @@ jobs:
           if xmlstarlet sel -t -m "/listings/listing[itemNumber='$item_number']/imageSmall" -v "." $xml_path | grep -q .; then
             # element already exists, update it with new value
             if xmlstarlet ed -u "/listings/listing[itemNumber='$item_number']/imageSmall" -v "$image_small" $xml_path > $temp_path; then
-                mv $temp_path $xml_path
-                echo "Updated imageSmall successfully"
+              mv $temp_path $xml_path
+              echo "Updated imageSmall successfully"
             else
-                echo "Error updating the XML file."
-                exit 1
+              echo "Error updating the XML file."
+              exit 1
             fi
           else
             # element does not exist, insert new subnode
             if xmlstarlet ed -s "/listings/listing[itemNumber='$item_number']" -t elem -n "imageSmall" -v "$image_small" $xml_path > $temp_path; then
-                mv $temp_path $xml_path
-                echo "Inserted imageSmall successfully"
+              mv $temp_path $xml_path
+              echo "Inserted imageSmall successfully"
             else
-                echo "Error updating the XML file."
-                exit 1
+              echo "Error updating the XML file."
+              exit 1
             fi
           fi
 
@@ -155,20 +155,20 @@ jobs:
           if xmlstarlet sel -t -m "/listings/listing[itemNumber='$item_number']/imageMedium" -v "." $xml_path | grep -q .; then
             # element already exists, update it with new value
             if xmlstarlet ed -u "/listings/listing[itemNumber='$item_number']/imageMedium" -v "$image_medium" $xml_path > $temp_path; then
-                mv $temp_path $xml_path
-                echo "Updated imageMedium successfully"
+              mv $temp_path $xml_path
+              echo "Updated imageMedium successfully"
             else
-                echo "Error updating the XML file."
-                exit 1
+              echo "Error updating the XML file."
+              exit 1
             fi
           else
             # element does not exist, insert new subnode
             if xmlstarlet ed -s "/listings/listing[itemNumber='$item_number']" -t elem -n "imageMedium" -v "$image_medium" $xml_path > $temp_path; then
-                mv $temp_path $xml_path
-                echo "Inserted imageMedium successfully"
+              mv $temp_path $xml_path
+              echo "Inserted imageMedium successfully"
             else
-                echo "Error updating the XML file."
-                exit 1
+              echo "Error updating the XML file."
+              exit 1
             fi
           fi
 
@@ -176,20 +176,20 @@ jobs:
           if xmlstarlet sel -t -m "/listings/listing[itemNumber='$item_number']/imageBig" -v "." $xml_path | grep -q .; then
             # element already exists, update it with new value
             if xmlstarlet ed -u "/listings/listing[itemNumber='$item_number']/imageBig" -v "$image_big" $xml_path > $temp_path; then
-                mv $temp_path $xml_path
-                echo "Updated imageBig successfully"
+              mv $temp_path $xml_path
+              echo "Updated imageBig successfully"
             else
-                echo "Error updating the XML file."
-                exit 1
+              echo "Error updating the XML file."
+              exit 1
             fi
           else
             # element does not exist, insert new subnode
             if xmlstarlet ed -s "/listings/listing[itemNumber='$item_number']" -t elem -n "imageBig" -v "$image_big" $xml_path > $temp_path; then
-                mv $temp_path $xml_path
-                echo "Inserted imageBig successfully"
+              mv $temp_path $xml_path
+              echo "Inserted imageBig successfully"
             else
-                echo "Error updating the XML file."
-                exit 1
+              echo "Error updating the XML file."
+              exit 1
             fi
           fi
 
diff --git a/.github/workflows/change-if-listing-sold.yaml b/.github/workflows/change-if-listing-sold.yaml
--- a/.github/workflows/change-if-listing-sold.yaml
+++ b/.github/workflows/change-if-listing-sold.yaml
@@ -67,10 +67,10 @@ jobs:
           is_sold="${{ inputs.is_sold }}"
 
           if xmlstarlet ed -u "/listings/listing[itemNumber='$item_number']/isSold" -v $is_sold $xml_path > $temp_path; then
-              mv $temp_path $xml_path
+            mv $temp_path $xml_path
           else
-              echo "Error updating the XML file."
-              exit 1
+            echo "Error updating the XML file."
+            exit 1
           fi
 
       - name: Commit changes
diff --git a/.github/workflows/delete-listing.yaml b/.github/workflows/delete-listing.yaml
--- a/.github/workflows/delete-listing.yaml
+++ b/.github/workflows/delete-listing.yaml
@@ -62,10 +62,10 @@ jobs:
           item_number="${{ inputs.item_number }}"
 
           if xmlstarlet ed -d "/listings/listing[itemNumber='$item_number']" $xml_path > $temp_path; then
-              mv $temp_path $xml_path
+            mv $temp_path $xml_path
           else
-              echo "Error updating the XML file."
-              exit 1
+            echo "Error updating the XML file."
+            exit 1
           fi
 
           # delete associated listing images
@@ -86,9 +86,12 @@ jobs:
       - name: Commit changes
         run: |
           git add $xml_path
-          git add static/images/small_${{ inputs.item_number }}.png
-          git add static/images/medium_${{ inputs.item_number }}.png
-          git add static/images/big_${{ inputs.item_number }}.png
+          for size in small medium big; do
+            image_path="static/images/${size}_${item_number}.png"
+            if [ ! -e "$image_path" ]; then
+              git rm "$image_path"
+            fi
+          done
           
           if [[ $(git diff --cached --name-only) ]]; then
             git commit -m "Remove listing: ${{ github.event.inputs.item_number }}"
